### ISSUE TITLE
[Win 10, Rack Pro v2.0.3, SDK v2.0.3] Opening browser with latest build crashes Rack

### ISSUE THREAD

**Issue by SteveRussell33** [Xenakios/XenakiosModules#2]
Fun times on the ```v2``` branch!
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffd888a1a03 in PortWithBackGround::draw (this=0x26eff281700, args=...) at C:/msys64/mingw64/include/c++/11.2.0/bits/shared_ptr_base.h:1295
1295    C:/msys64/mingw64/include/c++/11.2.0/bits/shared_ptr_base.h: No such file or directory.
(gdb) bt
#0  0x00007ffd888a1a03 in PortWithBackGround::draw (this=0x26eff281700, args=...) at C:/msys64/mingw64/include/c++/11.2.0/bits/shared_ptr_base.h:1295
#1  0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#2  0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#3  0x00007ffda0f3b552 in libRack!_ZN4rack3app12ModuleWidget4drawERKNS_6widget6Widget8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#4  0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#5  0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#6  0x00007ffda0f797b3 in libRack!_ZN4rack6widget17FramebufferWidget15drawFramebufferEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#7  0x00007ffda0f7a2cf in libRack!_ZN4rack6widget17FramebufferWidget6renderENS_4math3VecES3_NS2_4RectE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#8  0x00007ffda0f7a9a9 in libRack!_ZN4rack6widget17FramebufferWidget4drawERKNS0_6Widget8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#9  0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#10 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#11 0x00007ffda0f7c41d in libRack!_ZN4rack6widget10ZoomWidget4drawERKNS0_6Widget8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#12 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#13 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#14 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#15 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#16 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#17 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#18 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#19 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#20 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#21 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#22 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#23 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#24 0x00007ffda0f740fa in libRack!_ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#25 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#26 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#27 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#28 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#29 0x00007ffda0f7c07f in libRack!_ZN4rack6widget6Widget9drawChildEPS1_RKNS1_8DrawArgsEi () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#30 0x00007ffda0f7c192 in libRack!_ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#31 0x00007ffda0f7ed48 in libRack!_ZN4rack6window6Window4stepEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#32 0x00007ffda0f7f000 in libRack!_ZN4rack6window6Window3runEv () from /c/Program Files/VCV/Rack2 Pro/libRack.dll
#33 0x00007ff763e5119f in ?? ()
#34 0x00007ff763e41a63 in ?? ()
#35 0x00007ff763e413d4 in ?? ()
#36 0x00007ff763e414e6 in ?? ()
#37 0x00007ffdc9ce7034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#38 0x00007ffdcbcc2651 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#39 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by SteveRussell33** [comment]
Latest build good.
